### ISSUE TITLE
Handle missing DT_SCE_ORIGINAL_FILENAME

### ISSUE THREAD

**Issue by mikusp** [obhq/obliteration#612] opened 2024-02-05 00:05 UTC
`Error while running kernel: runtime linker initialization failed -> cannot open /mnt/sandbox/NPXS39041_000/eboot.bin -> cannot parse file info -> no DT_SCE_ORIGINAL_FILENAME.`

HB store and Itemzflow fail with that error message

**Comment by SuchAFuriousDeath** [comment] 2024-02-05 00:08
Duplicate of #349

**Closed** 2024-02-05 00:08 UTC
