### ISSUE TITLE
Add MacOS support for Intel

### ISSUE THREAD

**Issue by bayedieng** [obhq/obliteration#51] opened 2022-12-21 23:19 UTC
This will potentially be very difficult to do with decent performance but it would be quite nice to see macos and arm support (as that's what apple is increasingly moving towards). In regards to CPU emulation, the Unicorn Engine could be used but am personally unfamiliar with its performance and Licensing could be an issue since it's GPL. There is also the option of Rosetta but it is unclear how long apple will support it.

Regarding GPU emulation, since the core emulation is written in Rust rendering with WGPU might be a good option.

**Comment by ultimaweapon** [comment] 2022-12-22 02:10
Thanks for the information. Actually it is possible for ARM and macOS because we reassemble the whole executable and its dynamic modules. That mean we can replace the assemble part to output ARM instructions instead of x86. The problem is we need someone to work on this part because we don't have enough capacity.

**Comment by bayedieng** [comment] 2022-12-22 09:54
> The problem is we need someone to work on this part because we don't have enough capacity.
That is something that I could work on at some point given time or if no one else begins work on it first. 

In regards to gpu emulation, would wgpu be viable for this project?

**Comment by ultimaweapon** [comment] 2022-12-23 08:36
That will be awesome! I'll let you know when I finished the abstraction for the assemble part so you can create an implementation for ARM.

For WGPU I did not take a look yet. We have not reached the GPU part yet so I really have no idea how the PS4 GPU works in detail. The only thing I know is it uses unified memory, which is the reason why I chose to emulate system calls and reassemble the whole binary.

**Comment by ultimaweapon** [comment] 2022-12-23 09:45
In the mean time do you mind working on macOS CI and making the code buildable on macOS? Currently GitHub Actions does not provide M1 machine but we can use Intel until M1 is available.

**Comment by bayedieng** [comment] 2022-12-23 11:08
Alright, will attempt to get initial macos build support. I have an m1 mac though, not Intel.  I will not be able to test the Intel build locally but it should still work the same.

**Comment by ultimaweapon** [comment] 2023-01-18 04:39
@bayedieng cloud you check size of memory page on your macOS with M1 (e.g. `getconf PAGESIZE`)? I already got it from https://cpufun.substack.com/p/more-m1-fun-hardware-information but just want to make sure.

**Comment by ultimaweapon** [comment] 2023-01-18 22:22
Thanks!

**Comment by bayedieng** [comment] 2023-01-18 23:24
> Are you interested?
Yeah sure.

**Comment by ultimaweapon** [comment] 2023-01-18 23:31
@Mou-Ikkai do you want to join the organization? I already know the answer but just want to make sure :)

**Comment by Mou-Ikkai** [comment] 2023-01-18 23:51
@ultimaweapon That's gonna be a YESSSSSSSSS

**Comment by ultimaweapon** [comment] 2023-01-19 01:03
Just sent an invitation to both of you.

**Comment by ultimaweapon** [comment] 2023-01-19 01:06
BTW I already comeback from my personal things and online on our IRC channel but still quite busy with my full-time job.

**Comment by Mou-Ikkai** [comment] 2023-01-19 01:09
Joined the organization!

**Comment by ultimaweapon** [comment] 2023-01-20 12:25
I think we should close this issue because it has already become our official supported platform.

**Comment by bayedieng** [comment] 2023-01-20 13:10
Agreed precised in the title that it's only for intel. We''ll still need a separate issue for aarch64 support

**Closed** 2023-01-20 16:33 UTC
Labels: T-enhancement
