### ISSUE TITLE
Failed to load libSceFios2.prx

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [obhq/obliteration#527] opened 2023-12-17 02:23 UTC
<img width="545" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/35e19865-5550-4a05-b670-3f2e8baf34c4">

Basically almost all games (if not all) fail to load this library. Some before syscall 653 and the dmem ioctl, some after.

**Comment by ultimaweapon** [comment] 2023-12-17 02:50
We are missing something before this one. The game should be in chroot or jailed first so its root is not the root of FS.

**Comment by SuchAFuriousDeath** [comment] 2023-12-17 09:18
Where would that change something?

**Comment by SuchAFuriousDeath** [comment] 2023-12-17 09:40
More context here: 
<img width="576" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/42d0d98d-3c91-48ae-938e-88c9c4ce7e68">

**Comment by ultimaweapon** [comment] 2023-12-17 09:43
I really have no idea for now. Those logs are for game developer to tell them they need to copy some files to `app0/sce_module`, it have nothing to do with us.

**Comment by SuchAFuriousDeath** [comment] 2023-12-17 12:00
<img width="751" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/a82b2450-d223-4c01-a3cb-917a25c36d6d">

**Comment by ultimaweapon** [comment] 2023-12-17 15:18
I think I figured out the first part how this thing is working. The game start in chroot to `/mnt/sandbox/{id}_000`, which will cause syscall 585 to return 1 because the root of the game is not root FS. Then #375 will be called to get the path of `system` directory within the chroot path. So the filesystem the game see is something like:

```
/app0/eboot.bin
/RANDOMIZED_PATH/common/lib/libkernel.sprx
```

The problem is, how the game is able to access `/dev` in this case?

**Comment by ultimaweapon** [comment] 2023-12-17 16:40
@VocalFan can you check what is inside `/mnt/sandbox/{id}_000` when the game is running?

**Comment by VocalFan** [comment] 2023-12-17 16:47
Alright

**Comment by VocalFan** [comment] 2023-12-17 17:15
```
/app0 = Game contents (eboot, sce_sys, sce_module, game-data)
/av_contents = Symlink to root of disk's /user/av_contents folder
/c45DSN6z4l = System files, name is randomly generated (symlink to /system/common, common_temp (Which is just voice and agent TTS_cache, sqlite)
/data = Symlink to root of disk's /data folder
/dev = Response: 451 Requested action aborted. Local error in processing. | Error: Failed to retrieve directory listing
/host = Symlink to root of disk's /host folder.
/hostapp = Symlink to root of disk's /hostapp folder.
/system_tmp = Symlink to root of disk's /system_tmp folder.
```

So, system files IS randomized:

First launch: c45DSN6z4I
Second launch: QXuNNl0Zhn

**Comment by VocalFan** [comment] 2023-12-17 17:17
@ultimaweapon Just to make sure this pings ya ^

Also, upgraded my PS4 from an HDD to an SSD, feels way better :P

**Comment by ultimaweapon** [comment] 2023-12-18 02:01
Strange. Normally the symbolic link does not work if the destination file is outside the chroot.

**Comment by ultimaweapon** [comment] 2023-12-18 02:02
Another problem is the filesystem is exFAT, which does not support a symbolic link.

**Comment by VocalFan** [comment] 2023-12-18 02:33
If its not a symlink, then idk what, as when I double click those folders in the CUSA_app0, I get a duplicate of what that folder would be on root.

**Comment by VocalFan** [comment] 2023-12-18 15:05
> I guess we need to check SceSysCore to see how this thing is working.

I however do think the `dev` folder in `CUSA_app0` than the `dev` folder on the root of the drive, seeing as I can access the root drive's Dev folder, but the game's Dev folder returns that error.
`Response: 451 Requested action aborted. Local error in processing. | Error: Failed to retrieve directory listing`

**Comment by SuchAFuriousDeath** [comment] 2023-12-21 16:02
@ultimaweapon Could devfs be initially mounted on the game's directory?

**Comment by ultimaweapon** [comment] 2023-12-21 16:40
If you mean we just do that without understanding how those directors end up there then we should do that as a last resort. We should try to understand how the PS4 works as much as possible while we are reimplementing it. All of the information we gathered will come in handy later on when we hit any obstacles.

**Comment by SuchAFuriousDeath** [comment] 2023-12-21 17:02
No, I was just throwing around ideas about how the PS4 does it. Obviously, this is something we should get right,if we can.

**Comment by SuchAFuriousDeath** [comment] 2023-12-21 19:16
By the way the Ghidra Orbis loader is absolutely amazing.

**Comment by red-prig** [comment] 2023-12-22 14:10
Yes, these are not symbolic links, they are mounting folders, I assume that nullfs is used for mirroring folders

**Comment by ultimaweapon** [comment] 2023-12-23 08:27
Seems like those folders are mounted by the other process then it send a command to SceSysCore to start the program.

**Comment by ultimaweapon** [comment] 2023-12-23 08:35
Let's check mount list when the game is running to see if those folders are one of them.

**Comment by ultimaweapon** [comment] 2023-12-23 09:33
@VocalFan can you run this payload when the game is running? It will create `mount-list.txt` on the root of USB drive, which contains a mount list.

[dump-mntlist.zip](https://github.com/obhq/obliteration/files/13758586/dump-mntlist.zip)

**Comment by VocalFan** [comment] 2023-12-23 09:36
Better not break-

**Comment by SuchAFuriousDeath** [comment] 2023-12-24 19:22
@ultimaweapon Have you found the vfs_mountroot function?

**Comment by SuchAFuriousDeath** [comment] 2023-12-24 19:33
The start_init function also has some interesting things in it. Once you find vfs_mountroot, you can find it using function call trees.

**Comment by SuchAFuriousDeath** [comment] 2023-12-24 19:43
Of course: vfs_mountroot can be found by the strings vfs_mountroot_conf0, because the function is inlined.
<img width="554" alt="image" src="https://github.com/obhq/obliteration/assets/48620541/3f5c97c9-2909-4864-b287-7359c0fe72d7">

**Comment by VocalFan** [comment] 2023-12-25 20:24
> @VocalFan can you run this payload when the game is running? It will create `mount-list.txt` on the root of USB drive, which contains a mount list.
> 
> [dump-mntlist.zip](https://github.com/obhq/obliteration/files/13758586/dump-mntlist.zip)

Back from Christmas, will doooo

**Comment by VocalFan** [comment] 2023-12-25 20:30
> Better not break-

I can't believe you.

*The payload runner notifies me it ran the payload, but there is no error msg or output file.

**Comment by SuchAFuriousDeath** [comment] 2023-12-27 23:47
By the way I tried rpcsx and after this, we'll most likely reach socketex, shm_open, evf_open, kqueue, /dev/rng, /dev/gc, evf_create and osem_create. Not necessarily in this order and not necessarily for all games.

**Comment by SuchAFuriousDeath** [comment] 2023-12-27 23:55
Also, kern.fsst_param

**Comment by ultimaweapon** [comment] 2023-12-28 05:40
Beware that some parts of RPCSX are licensed under GPL, which means we can't incorporate those codes.

**Comment by SuchAFuriousDeath** [comment] 2023-12-28 07:46
I haven't looked at the code, I just looked at the output logs :D

**Comment by VocalFan** [comment] 2023-12-28 19:38
> > Better not break-
> 
> I can't believe you.
> 
> *The payload runner notifies me it ran the payload, but there is no error msg or output file.

Uh, lmk if you find a fix or something @ultimaweapon

**Comment by ultimaweapon** [comment] 2023-12-29 07:06
> > > Better not break-
> > 
> > 
> > I can't believe you.
> > *The payload runner notifies me it ran the payload, but there is no error msg or output file.
> 
> Uh, lmk if you find a fix or something @ultimaweapon

Try this one:
[dump-mntlist.zip](https://github.com/obhq/obliteration/files/13791545/dump-mntlist.zip)

**Comment by VocalFan** [comment] 2023-12-29 08:10
Same as before. "Payload received from 127.0.0.1" notif, then nothing.

**Comment by ultimaweapon** [comment] 2023-12-29 09:18
No idea what wrong here. Here is the code is someone want to try:

```c
#include <ps4.h>

struct fsid {
	int val[2];
};

struct statfs {
	unsigned f_version;
	unsigned f_type;
	long field2_0x8;
	long field3_0x10;
	long field4_0x18;
	long field5_0x20;
	long field6_0x28;
	long field7_0x30;
	long field8_0x38;
	long field9_0x40;
	long field10_0x48;
	long field11_0x50;
	long field12_0x58;
	long field13_0x60;
	long field14_0x68;
	long field15_0x70;
	long field16_0x78;
	long field17_0x80;
	long field18_0x88;
	long field19_0x90;
	long field20_0x98;
	long field21_0xa0;
	long field22_0xa8;
	long field23_0xb0;
	char field24_0xb8;
	char field25_0xb9;
	char field26_0xba;
	char field27_0xbb;
	int f_owner;
	struct fsid f_fsid;
	long field30_0xc8;
	long field31_0xd0;
	long field32_0xd8;
	long field33_0xe0;
	long field34_0xe8;
	long field35_0xf0;
	long field36_0xf8;
	long field37_0x100;
	long field38_0x108;
	long field39_0x110;
	char f_fstypename[16];
	char f_mntfromname[88];
	char f_mntonname[88];
};

_Static_assert(sizeof(struct statfs) == 0x1d8, "assert1");

int getfsstat(struct statfs *, size_t, int);

int _main(struct thread *td) {
	size_t len;
	struct statfs *buf;
	int res, i;
	FILE *fp;

	initKernel();
	initLibc();
	jailbreak();
	initSysUtil();

	// allocate buffer
	len = sizeof(*buf) * 128;
	buf = malloc(len);

	if (!buf) {
		printf_notification("Failed to allocate %u bytes of memory.", len);
		return 0;
	}

	// get mount list
	res = getfsstat(buf, len, 1);

	if (res < 0) {
		free(buf);
		printf_notification("Failed to get mount list.");
		return 0;
	}

	// write to usb drive
	fp = fopen("/mnt/usb0/mount-list.txt", "w");

	if (!fp) {
		free(buf);
		printf_notification("Failed to create /mnt/usb0/mount-list.txt.");
		return 0;
	}

	for (i = 0; i < res; i++) {
		struct statfs *s = buf + i;

		fprintf(fp, "%s\t%s\t%s\r\n", s->f_fstypename, s->f_mntfromname, s->f_mntonname);
	}

	fclose(fp);
	free(buf);

	printf_notification("Mount list dump complete!");

	return 0;
}

SYSCALL(getfsstat, 395);
```

**Comment by ultimaweapon** [comment] 2023-12-29 10:13
@VocalFan try again with this version:
[dump-mntlist.zip](https://github.com/obhq/obliteration/files/13792582/dump-mntlist.zip)

**Comment by VocalFan** [comment] 2023-12-29 18:46
Once again, nothing.

**Comment by ultimaweapon** [comment] 2023-12-30 06:01
This is... Weird.

**Comment by VocalFan** [comment] 2023-12-30 07:23
Yeah, just...

'Payload received from 127.0.0.1'

*Nothing. No notification or blinking from my USB's activity LED, and plugging my USB into my PC gives nothing.*

**Comment by ultimaweapon** [comment] 2023-12-30 08:58
@gandalfthewhite19890404 does your firmware is also 9.0? If yes can you try the above payload?

**Comment by red-prig** [comment] 2023-12-30 18:50
I tried it, same thing

**Comment by ultimaweapon** [comment] 2023-12-30 18:53
Thanks! Seems like there are something weird there...

**Comment by VocalFan** [comment] 2023-12-30 21:28
Either that or we need to find a way to magically make payloads in Rust.

**Comment by SuchAFuriousDeath** [comment] 2023-12-30 21:38
@VocalFan Can you try and add a print statements before the malloc and run it?

**Comment by SuchAFuriousDeath** [comment] 2023-12-30 21:40
And also... shouldn't it be sizeof(struct statfs)? I don't have much experience in C.

**Comment by SuchAFuriousDeath** [comment] 2023-12-30 21:53
Maybe ... do a binary search to find out when it stops working.

**Comment by ultimaweapon** [comment] 2023-12-31 05:03
I don't think Rust will solve the problem and the problem should not be malloc.

**Comment by ultimaweapon** [comment] 2023-12-31 07:07
@VocalFan try this one:
[dump-mntlist.zip](https://github.com/obhq/obliteration/files/13800467/dump-mntlist.zip)

**Comment by SuchAFuriousDeath** [comment] 2024-01-08 08:44
@red-prig Can you try this payload?

**Comment by red-prig** [comment] 2024-01-08 15:02
There is only one message "Mount list dump complete" but for some reason the file is not created (it looks like some kind of bug with usb mounting?), you can try saving the file to /data/* ???

**Comment by ultimaweapon** [comment] 2024-01-08 16:12
Thanks! The reason it does not create any files is because I removed the corresponding code. Now we know it is broken at `fopen` line.

**Comment by red-prig** [comment] 2024-01-08 17:01
You can make everything simpler, just write to stdout, that is, write(1,*,*) and I will see it in klog

**Comment by ultimaweapon** [comment] 2024-01-09 14:43
This one should work:
[dump-mntlist.zip](https://github.com/obhq/obliteration/files/13875113/dump-mntlist.zip)

I did not write to stdout yet because... I'm too lazy 😂.

**Comment by SuchAFuriousDeath** [comment] 2024-01-09 15:38
@red-prig

**Comment by red-prig** [comment] 2024-01-09 16:18
Still no files are being created.

**Comment by red-prig** [comment] 2024-01-09 16:20
```
  else {
    iVar1 = syscall_11(5,&local_ea8);
    if (-1 < iVar1) {
      lVar6 = 0;
      iVar2 = open(s_/mnt/usb0/mount-list.txt_000019e1,0x601,0777);
      if (-1 < iVar2) {
```

**Comment by ultimaweapon** [comment] 2024-01-09 16:25
Thanks for testing. No idea why it does not work. At least `open` should succeed because it was working with auth-dumper before.

**Comment by red-prig** [comment] 2024-01-09 16:26
wtf is syscall 11 ??? on PS4 it's just nosys

**Comment by SuchAFuriousDeath** [comment] 2024-01-09 16:31
Do we need it in a file? Wouldn't printf_notification be enough instead of the write syscall?

**Comment by red-prig** [comment] 2024-01-09 16:55
omg it work! 
[mount-list.txt](https://github.com/obhq/obliteration/files/13876694/mount-list.txt)

**Comment by SuchAFuriousDeath** [comment] 2024-01-09 17:07
Damn, that's a lot of mounts :D

**Comment by ultimaweapon** [comment] 2024-01-11 16:45
Seems like there are more than what we saw in the list.

**Comment by SuchAFuriousDeath** [comment] 2024-01-11 18:24
> Seems like there are more than what we saw in the list.

Judging from what?

**Comment by ultimaweapon** [comment] 2024-01-12 15:46
Because I was allocated a buffer for 128 entries and the list make use all of it.

**Comment by SuchAFuriousDeath** [comment] 2024-01-12 16:02
Oh :eyes:

**Comment by ultimaweapon** [comment] 2024-01-13 04:43
A new version that supports up to 8192 entries:
[dump-mntlist.zip](https://github.com/obhq/obliteration/files/13926794/dump-mntlist.zip)

**Comment by ultimaweapon** [comment] 2024-01-14 04:33
@VocalFan can you run the above payload with at least one game disk inserted?

**Comment by VocalFan** [comment] 2024-01-14 04:34
> @VocalFan can you run the above payload with at least one game disk inserted?

Will do tomorrow when I'm near my PS4.

**Comment by red-prig** [comment] 2024-01-14 12:57
[mount-list.txt](https://github.com/obhq/obliteration/files/13931543/mount-list.txt)

**Comment by ultimaweapon** [comment] 2024-01-14 13:08
Thanks!

**Comment by ultimaweapon** [comment] 2024-01-15 14:24
The good news is we already got what we need from @red-prig so you don't need to run this anymore.

**Comment by SuchAFuriousDeath** [comment] 2024-01-15 23:01
I wanted to play around a bit with LLVM, but it turns out the FS rework took back so much that we don't even reach the Execution Engine specific part of the code :D

**Comment by SuchAFuriousDeath** [comment] 2024-02-18 22:39
@ultimaweapon Ok, I'm confused now. After I implementing TempFs::root, we still fail with the same error of failing to lookup /app/eboot.bin. What am I supposed to do?

**Comment by SuchAFuriousDeath** [comment] 2024-02-19 00:34
I think I get it now. We have to change the root of the process, right? Then it makes sense. The good thing is, we probably don't have to try super hard with tmpfs for now, because we only need to pass through it to get the file, we don't actually need to write anything to it for now.

**Comment by ultimaweapon** [comment] 2024-04-01 16:33
Thanks everyone! Now our new FS has been mostly done and we can load this library correctly so I will close this.

**Closed by ultimaweapon** 2024-04-01 16:33 UTC
Labels: T-enhancement
