### ISSUE TITLE
Unimplemented Syscall 608

### ISSUE THREAD

**Issue by VocalFan** [obhq/obliteration#265] opened 2023-07-21 02:44 UTC
`thread 'main' panicked at 'not yet implemented: syscall 608 at 0x0000000000001eba on /system/common/lib/libkernel.sprx', kernel\src\syscalls\mod.rs:68:18`

CUSTOM PS4 SYSCALL

<html>
<body>

608 | <=1.01? | sys_dynlib_get_info_ex | int sys_dynlib_get_info_ex(int moduleHandle, struct Unk *unk, int *destModuleInfoEx)
-- | -- | -- | --

</body>
</html>

**Comment by VocalFan** [comment] 2023-07-28 03:55
@ultimaweapon Latest PR gives `Syscall 608 failed: invalid argument.`

Just letting ya know when you do part 2.

**Comment by VocalFan** [comment] 2023-07-29 02:47
@ultimaweapon 

```
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000005ed0:kernel\src/main.rs:115
Starting Obliteration Kernel.
System directory    : G:\obSTORAGE\dev_sys
Game directory      : G:\obSTORAGE\dev_hdd0\CUSA04518
Debug dump directory: C:\Users\Windows Games\AppData\Local\OBHQ\Obliteration\kernel
++++++++++++++++++ I [00:00:00:00:001]:0x0000000000005ed0:kernel\src/main.rs:133
Initializing file system.
++++++++++++++++++ I [00:00:00:00:002]:0x0000000000005ed0:kernel\src/main.rs:144
Initializing memory manager.
++++++++++++++++++ I [00:00:00:00:002]:0x0000000000005ed0:kernel\src/main.rs:147
Page size is             : 4096
Allocation granularity is: 65536
++++++++++++++++++ I [00:00:00:00:002]:0x0000000000005ed0:kernel\src/main.rs:160
Initializing virtual process.
++++++++++++++++++ P [00:00:00:00:003]:0x0000000000005ed0:G:\GitHub\obliteration\src\tls\src\lib.rs:60
called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Uncategorized, message: "The handle is invalid." }
```

**Comment by VocalFan** [comment] 2023-07-29 02:55
By that reaction... Is that unexpected?

**Comment by VocalFan** [comment] 2023-07-29 02:59
Oh! If I do it in the Kernel using VSCode:

```
; Symbol: __rust_start_panic
; Source: \rustc\8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\panic_abort\src\lib.rs:32
7FF6C2F98DA0: 50                         push   rax
7FF6C2F98DA1: B9 07 00 00 00             mov    ecx, 0x7
7FF6C2F98DA6: CD 29                      int    0x29
7FF6C2F98DA8: 0F 0B                      ud2    

++++++++++++++++++ P [00:00:00:00:016]:0x00000000000027a4:G:\GitHub\obliteration\src\tls\src\lib.rs:60
called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }

**Comment by ultimaweapon** [comment] 2023-07-29 04:05
Nope. It is my bug. I was using a wrong comparison operator. Should be fixed by #281.

**Comment by VocalFan** [comment] 2023-07-29 23:07
> Nope. It is my bug. I was using a wrong comparison operator. Should be fixed by #281.

Back to this:

```
++++++++++++++++++ I [00:00:00:00:513]:0x000000000000139c:kernel\src/main.rs:248
353 patch(es) have been applied to /system/common/lib/libkernel.sprx.
187 patch(es) have been applied to /system/common/lib/libSceLibcInternal.sprx.
2 module(s) have been patched successfully.
++++++++++++++++++ I [00:00:00:00:514]:0x000000000000139c:kernel\src/main.rs:298
Starting application.
++++++++++++++++++ W [00:00:00:00:520]:0x000000000000139c:kernel\src\syscalls\mod.rs:68
Syscall 608 failed: invalid argument.
++++++++++++++++++ P [00:00:00:00:521]:0x000000000000139c:kernel\src\syscalls\mod.rs:83
not yet implemented: int 0x44 at at 0x000000000002b13a on /system/common/lib/libkernel.sprx
```

Exception 0xc0000409 encountered at address 0x7ff6aee61b26

**Comment by ultimaweapon** [comment] 2023-07-29 23:41
Better to create a separated issue.

**Comment by VocalFan** [comment] 2023-07-30 01:28
Not really, because it still comes from syscall 608

**Comment by ultimaweapon** [comment] 2023-07-30 02:57
It is unlikely to be fixed along with this because I have no idea what the problem is.

**Comment by VocalFan** [comment] 2023-08-01 00:30
> It is unlikely to be fixed along with this because I have no idea what the problem is.

I mean, it's just coming from

```
        if size != size_of::<DynlibInfoEx>() {
            return Err(Error::Raw(EINVAL));
        }
```

**Comment by ultimaweapon** [comment] 2023-08-01 01:06
That one should not cause the error you that you have encountered.

**Comment by VocalFan** [comment] 2023-08-01 01:37
Ehh... EINVAL is "invalid argument"

```
Syscall 608 failed: invalid argument.
```

**Comment by ultimaweapon** [comment] 2023-08-01 02:33
I mean exception 0xc0000409.

**Comment by VocalFan** [comment] 2023-08-01 02:36
Ah, yes, that's just the exception that occurs from having the invalid argument.

**Comment by ultimaweapon** [comment] 2023-08-01 03:10
No. This exception should not happened here.

**Comment by VocalFan** [comment] 2023-08-01 03:14
Mmm... It only shows from the Rust Panic that VS Code gives.

**Comment by VocalFan** [comment] 2023-08-01 03:26
So, might be a domino effect. Fix the error, stops everything else from toppling over.

**Comment by VocalFan** [comment] 2023-08-06 15:24
Guess a good thing is that this adds a lot of functions you'll be able to use if another syscall needs them, haha.

**Comment by ultimaweapon** [comment] 2023-08-06 20:57
We can expect when one game boots, most games probably boot too.

**Closed** 2023-08-25 10:14 UTC
Labels: T-enhancement
